### ISSUE TITLE
php artisan doctrine not recognized

### ISSUE THREAD

**Issue by ghost** [paolooo/laravel-doctrine#1]
I've got Laravel version 5.

I install your composer package as your instructions say, and add the service provide in config/app.php under providers.

When I run the php artisan commands, it does not recognize the doctrine name. 

Any ideas?

I have also run a composer dump-autoload to make sure.

**Comment by paolooo** [comment]
Hi @jamestrusleroval,

Did you add the doctrine configs on .env file and phpunit.xml?

**For local or prod environment** - for more information about doctrine's proxy config, see http://doctrine-orm.readthedocs.org/en/latest/reference/advanced-configuration.html

```
# .env
...

DOCTRINE_PROXY_AUTOGENERATED=false
DOCTRINE_PROXY_NAMESPACE=Acme\Domain\Model\Proxy
DOCTRINE_PROXY_DIR=app/Domain/Model/Proxy
DOCTRINE_MAPPING_DIR=app/Domain/Model
```

**For testing environment**

```
# phpunit.xml

<?xml version="1.0" encoding="UTF-8"?>
<phpunit ...>
    ....
    <php>
        ...
        <env name="DB_DATABASE" value="storage/tests/db.sqlite"/>
    </php>
</phpunit>
```

Let me know. Thanks.

**Comment by ghost** [comment]
I have all of the above.

I have also now added to the commands array in `app/console/Kernel.php`

Now when I run the command, I get this:

```
Target [Doctrine\ORM\EntityManager] is not instantiable
```

It seems the service provider does not get called for console commands, and thus your command registration does not work... and when you add the command to the Kernel.php, it doesn't have the instantiation bindings set up.

**Comment by paolooo** [comment]
You don't have to add that on `app/console/Kernel.php` the service provider will automatically do that.

I cannot reproduce this issue. Can you please tell your PHP version? and is it possible for me to test your code? I just downloaded a fresh L5, install laravel-doctrine package, set up configs, and run command `php artisan doctrine` and it works just fine.

hmmm

**Comment by ghost** [comment]
Here are the files: https://github.com/jamestrusleroval/VanillaLaravel/tree/develop I've removed from Kernel.php for you.

Take a look at the .env-example, it's a copy of the real .env.

Thanks for taking a look at this!

**Comment by paolooo** [comment]
I'll try to run this on my local machine. Let you know.

What's your php version again?

**Comment by ghost** [comment]
Ah, good point. It's 5.4, sorry to miss out that detail :)

**Comment by paolooo** [comment]
I see.. that's why... PHP 5.4 doesn't support class name resolution via `::class`.

http://php.net/manual/en/migration55.new-features.php

Can you please try to edit this file:

https://github.com/paolooo/laravel-doctrine/blob/master/src/LaravelDoctrineServiceProvider.php#L21

change `EntityManager::class` to `'\Doctrine\ORM\EntityManager'`. Let me know.

**Comment by ghost** [comment]
This hasn't worked. In fact, when I remove the addition to the Kernel.php that I told you about, I still get the Command "doctrine" is not found. I have uploaded the version to development so you can see the changes I have made.

**Comment by paolooo** [comment]
I've downloaded your repo, run, and it works just fine.

```
$ git clone https://github.com/jamestrusleroval/VanillaLaravel.git
$ cd VanillaLaravel
$ composer require "paolooo/laravel-doctrine":"0.1.*@dev"
```

Edited `app/local/config.php. Added the following code on`$providers` array @ line 138

```
     'Paolooo\LaravelDoctrine\LaravelDoctrineServiceProvider',
```

Created `.env` file

```
$ cp .env.example .env
```

Edit `.env` file

```
APP_ENV=local
APP_DEBUG=true
APP_KEY=GOdMIcogCDe1D61a8YFvwyYTheQ9Bjqq

DB_HOST=localhost
DB_DATABASE=vanillalaravel5
DB_USERNAME=root
DB_PASSWORD=

CACHE_DRIVER=file
SESSION_DRIVER=file

DOCTRINE_PROXY_AUTOGENERATED=false
DOCTRINE_PROXY_NAMESPACE=Acme\Domain\Model\Proxy
DOCTRINE_PROXY_DIR=app/Domain/Model/Proxy
DOCTRINE_MAPPING_DIR=app/Domain/Model
```

Run artisan

```
$ php artisan doctrine
```

Question, why do you have `app/local` directory?

**Comment by ghost** [comment]
you can place folders inside the app/config to have different environments... So local fodler was for local environment. I've removed it just incase it was causing an issue. I will take a proper look at all of this when I get some time. Thanks for all your hard work... 

Can I recommend re-opening :) ?

**Comment by paolooo** [comment]
@jamestrusleroval as long as the issue is all about the laravel-doctrine package, I would love to reopen this but the issue is not about this package. It's how you config your app.

Laravel 5 has different configuration. I suggest you use that instead. It uses `.env` file, but if you want to use `config/local` directory, I think it wouldn't be a problem.

http://laravel.com/docs/5.0/configuration#environment-configuration

If you have `config/local` then use `config/local/app.php`, otherwise, use `config/app.php` to insert the service provider value for this package.

Thanks.

**Comment by ghost** [comment]
Figured it out. I had to run: `php artisan config:clear`
