### ISSUE TITLE
php artisan doctrine orm:schema-tool:update

### ISSUE THREAD

**Issue by ghost** [paolooo/laravel-doctrine#2]
Use the

`php artisan doctrine orm:schema-tool:create` to create your db table, for let's, say a User

Then change one of the properties, like:

```
/**
 * @Column(type="integer")
 * @var int
 **/
protected $name;
```

Then use the `php artisan doctrine orm:schema-tool:update`

Does yours actually update the users table? If I just use the default Doctrine 2 set up, it works okay... Any reason why that might not be working... something to do with the setup used perhaps?

**Comment by paolooo** [comment]
In my case, I clear the metadata cache first by:

```
$ php artisan doctrine orm:clear-cache:metadata
$ php artisan doctrine orm:schema-tool:update
```

**Comment by ghost** [comment]
Thank you very much. This is a great plugin... Nice and easy to understand the code Thank you. All working now.

**Comment by php-daddy** [comment]
Cool, glad that you are happy with it. Thanks for your support. :)

**Comment by paolooo** [comment]
Cool, glad that you are happy with it. Thanks for your support. :)
